routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::post('/new_register', 'UserController@new_register');

// Route::post('/registry', 'HomeController@register');

Auth::routes();
Route::group(['middleware' => ['auth']], function () {

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'HomeController@profile');

Route::get('teachers/{id}', 'HomeController@index_attendance');

Route::resource('branch', 'BranchController');
Route::resource('branchadmin', 'BranchadminController');
Route::resource('group', 'GroupController');
Route::resource('ruller', 'RullerController');
Route::get('ruller/view', 'RullerController@view');

Route::resource('parents', 'ParentsController');
Route::resource('students', 'StudentsController');

Route::resource('lesson', 'LessonController');


Route::get('profile', 'UserController@profile');
Route::post('profile/update', 'UserController@profile_update');
Route::get('sertified/{id}', 'SertifiedController@create');
Route::post('sertified/{id}', 'SertifiedController@store');
Route::get('sertified/delete/{id}', 'SertifiedController@destroy');

Route::get('/all_messages', 'ChatController@all_messages');




Route::get('/student/{id}', 'InviteController@check');

// Route::resource('reseption', 'ReseptionController');



Route::get('reseption/access', 'ReseptionController@access');
Route::post('reseption/{id}', 'ReseptionController@update');







// InviteController
Route::post('/invite/connect', 'InviteController@invite');

Route::resource('users', 'UserController');
Route::post('/user/status/{id}', 'HomeController@status');



Route::get('attendance/{id}', 'AttendanceController@index');
Route::post('/attendance/check', 'AttendanceController@check');


// ChatController

Route::get('/compose', 'ChatController@compose');
Route::get('/inbox', 'ChatController@inbox');
Route::get('/sent-mail', 'ChatController@sent_mail');

Route::get('/single-message/{id}', 'ChatController@messages_show');


Route::post('/compose/insert', 'ChatController@insert');


});

app/Lesson.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lesson extends Model
{
    protected $table="lesson";

     function ruller()
    {
    	return $this->hasMany('App\Ruller');
    }
}

app/Http/Controllers/LessonController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Lesson;


class LessonController extends Controller
{
   

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
       public function index()
    {
        $lesson = Lesson::all();
        return view('/lesson/index',compact('lesson'));
    }
    public function create()
    {
        return view('/lesson/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
   public function store(Request $request){

        $lesson = new Lesson;
            $lesson->name=$request->name;

        $lesson->save();
       return back()->with('success', 'Uğurlu! Fenn Əlavə Edildi.');
        
    }
     

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $lesson = Lesson::find($id);

        return view('lesson/edit',compact('lesson'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request,$id)
    {
        $lesson = Lesson::find($id);
        
         $lesson->name=$request->name;

        $lesson->save();

        return redirect('/lesson')->with('success', 'Uğurlu! Məlumatlar Dəyişdirildi.');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
         $lesson = Lesson::find($id);

        $lesson->delete();
        return back()->with('delete', 'Uğurlu! Fenn Silindi.'); 
        }

}

resources/views/lesson/create.blade.php
 
@extends('layouts.app')


@section('content')
<div class="container">

  <div class="row">
                    <div  style="text-align: center;" class="col-sm-12">
                        <div  class="white-box p-l-20 p-r-20">
                        <i  class="fa fa-book fa-5x"></i> 
                            <h3 class="box-title m-b-0">Dərs Adını Daxil Et</h3>
                          
                            <div class="row">
                                <div class="col-md-12">
 <form action="/lesson" enctype="multipart/form-data" method="POST" class="form-horizontal">
                                  
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                          
                                        <div class="form-group">
                                             <div class="col-sm-4"></div>

                                            <div  class="col-md-4">
                                                <input placeholder="Dərs Adı Əlavə Et" name="name" type="text" class="form-control form-control-line">
                                                 </div>
                                        </div> 
                                        
                                        <div class="form-group">
                                             <div class="col-sm-4"></div>
                                            <div class="col-sm-4">
                                                <input type="submit" value="Göndər" class="btn btn-block btn-success" placeholder="Helping text"> 
                                                 </div>
                                        </div>
@if ($message = Session::get('success'))
                  <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button> 
                          <strong>{{ $message }}</strong>
                  </div>
                @endif
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

<!-- ent layout -->


@endsection

resources/views/lesson/edit.blade.php
@extends('layouts.app')


@section('content')
<div class="container">

  <div class="row">
                    <div  style="text-align: center;" class="col-sm-12">
                        <div  class="white-box p-l-20 p-r-20">
                        <i  class="fa fa-edit fa-5x"></i>
                            <h3 class="box-title m-b-0">Dərs Adını Dəyiş</h3>

                            <div class="row">
                                <div class="col-md-12">
              <form action="{{route('lesson.update', $lesson->id)}}" enctype="multipart/form-data" method="POST" class="form-horizontal">

                 <input type="hidden" name="_method" value="PATCH">
                 {{ csrf_field() }}

                                        <div class="form-group">
                                             <div class="col-sm-4"></div>

                                            <div  class="col-md-4">
                                                <input value="{{$lesson->name}}" name="name" type="text" class="form-control form-control-line">
                                                 </div>
                                        </div>

                                        <div class="form-group">
                                             <div class="col-sm-4"></div>
                                            <div class="col-sm-4">
                                                <input type="submit" value="Dəyiş" class="btn btn-block btn-success">
                                                 </div>
                                        </div>

                                    </form>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
@endsection

resources/views/lesson/index.blade.php
@extends('layouts.app')

@section('content')
<!-- start -->
<div class="container">
  <div id="page-wrapper">
  <!-- div class="container-fluid">
      <div class="row bg-title">
          <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
              <h4 class="page-title"></h4> </div>
          <!-- /.col-lg-12 -->
     <!--  </div>  -->
      <!-- /row -->
      <div class="row">
          <div class="col-sm-12">
              <div class="white-box">
                  <h3 class="box-title">Sistemdə Olan Bütün Dərslər </h3>

                  <div class="table-responsive">
                      <table class="table color-table primary-table">
                          <thead>
                              <tr>
                                  <th>#</th>
                                  <th>Dərs Adı</th>
                                 <th><i class="fa fa-edit" aria-hidden="true"></i></th>
                                 <th><i class="fa fa-trash-o" aria-hidden="true"></i></th>

                              </tr>
                          </thead>
                          <tbody>

                          @foreach ($lesson as $lesso)
                              <tr>
                                  <td>1</td>
                                  <td>{{$lesso->name}}</td>

                                  <td><a class="btn btn-warning" href="/lesson/{{$lesso->id}}/edit">Redaktə Et</a></td>
                                <td>
                                   <form method="POST" action="{{ route('lesson.destroy', $lesso->id) }}">
                                   {{csrf_field()}}
    <input type="hidden" name="_method" value="DELETE" />
    <button type="submit" class="btn btn-danger">Sil</button>

</form>
</td>   

                              </tr>
                              @endforeach

                          </tbody>

                      </table>
                      @if ($message = Session::get('success'))
                  <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                          <strong>{{ $message }}</strong>
                  </div>
                @endif
                @if ($message = Session::get('delete'))
                  <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                          <strong>{{ $message }}</strong>
                  </div>
                @endif
                  </div>
              </div>
          </div>
      </div>
<!-- endlay out -->
@stop