routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::post('/new_register', 'UserController@new_register');

// Route::post('/registry', 'HomeController@register');

Auth::routes();
Route::group(['middleware' => ['auth']], function () {

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'HomeController@profile');

Route::get('teachers/{id}', 'HomeController@index_attendance');

Route::resource('branch', 'BranchController');
Route::resource('branchadmin', 'BranchadminController');
Route::resource('group', 'GroupController');
Route::resource('ruller', 'RullerController');
Route::get('ruller/view', 'RullerController@view');

Route::resource('parents', 'ParentsController');
Route::resource('students', 'StudentsController');

Route::resource('lesson', 'LessonController');


Route::get('profile', 'UserController@profile');
Route::post('profile/update', 'UserController@profile_update');
Route::get('sertified/{id}', 'SertifiedController@create');
Route::post('sertified/{id}', 'SertifiedController@store');
Route::get('sertified/delete/{id}', 'SertifiedController@destroy');

Route::get('/all_messages', 'ChatController@all_messages');




Route::get('/student/{id}', 'InviteController@check');

// Route::resource('reseption', 'ReseptionController');



Route::get('reseption/access', 'ReseptionController@access');
Route::post('reseption/{id}', 'ReseptionController@update');







// InviteController
Route::post('/invite/connect', 'InviteController@invite');

Route::resource('users', 'UserController');
Route::post('/user/status/{id}', 'HomeController@status');



Route::get('attendance/{id}', 'AttendanceController@index');
Route::post('/attendance/check', 'AttendanceController@check');


// ChatController

Route::get('/compose', 'ChatController@compose');
Route::get('/inbox', 'ChatController@inbox');
Route::get('/sent-mail', 'ChatController@sent_mail');

Route::get('/single-message/{id}', 'ChatController@messages_show');


Route::post('/compose/insert', 'ChatController@insert');


});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','group_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

     public function student()
    {
        return $this->belongsTo('App\Students','id','user_id');
    }
     public function parents()
    {
        return $this->hasMany('App\Parents');
    }
    public function attendance()
    {
        return $this->hasMany('App\Attendance');
    }
     public function sertified()
    {
        return $this->hasMany('App\Sertified');
    }
     public function branch()
    {
        return $this->belongsTo('App\Branch');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\User;
use App\Branch;
use App\Branchadmin;
use App\Teacher;
use App\Reseption;
use App\Parents;
use App\Students;
use App\Invite;
use App\Group;



class UserController extends Controller
{

  public function new_register(Request $request)
  {

        $user = new User;
        $user->name=$request->name;
        $user->surname=$request->surname;
        $user->email=$request->email;
        $user->mobile=$request->mobile;
        $user->group_id=$request->group_id;


        if ($request->group_id) {
          $group = Group::where('id',$request->group_id)->first();
          $user->branch_id=$group->branch_id;
        }

        $userfind = User::where('email',$request->email)->first();
        if ($userfind) {
          return back()->with('unsuccess', 'Uğursuz! Belə Bir e-poçt var.');
        }

        $user->type=$request->type;
        $pass=$request->password;
        $user->password=bcrypt($pass);
        $user->save();

        if ($request->type==1) {

        $student = new Students;
            $student->user_id=$user->id;
            $student->kart_id=rand();
            $student->save();
            // return back();

        }

        if ($request->type==2) {

        $parents = new Parents;
            $parents->user_id=$user->id;
            $parents->branch_id=$group->branch_id;
            $parents->save();
        }
        $credentials = array(
          'email' => $request->email,
          'password' => $request->password
        );

        if (Auth::attempt($credentials)) {
          return redirect('home');
        }
  }

public function index(){
  if (Auth::user()->type==0) {

     $users = User::all();

    return view('users.index',compact('users'));

  }




     if (Auth::user()->type==3) {

           $branch_id = Auth::user()->branch_id;
           $users = User::where('branch_id',$branch_id)->get();
           return view('reseption.index' ,compact('users'));
         }


     if (Auth::user()->type==6) {

           $branch_id = Auth::user()->branch_id;
           $users = User::where('branch_id',$branch_id)->get();
           return view('branchadmin.index' ,compact('users'));
         }
       }

    public function create()
    {
  if (Auth::user()->type==0) {


    $branch = Branch::all();

    return view('users.create',compact('branch'));
    }

    if (Auth::user()->type==6) {
    $branch = Branch::all();

           $branch_id = Auth::user()->branch_id;
           $gro = Group::where('branch_id',$branch_id)->get();
    return view('users.create',compact('gro','branch'));



  }

  else{
    return ('Error');
  }

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $fileName           =$request->img->getClientOriginalName();
      $newName            =time().'_'.$fileName;
      $request->img->move('uploads/',$newName);

            $user = new User;
            $user->surname=$request->surname;
            $user->name=$request->name;
            $user->email=$request->email;
            $user->mobile=$request->mobile;
            $user->about=$request->about;
            $user->type=$request->type;
            $user->date=$request->date;
            $user->branch_id=$request->branch_id;
            $user->group_id=$request->group_id;
            $pass=$request->password;
            $user->password=bcrypt($pass);
            $user->img=$newName;

            $user->save();

              if ($request->type==6) {
            $branchadmin = new Branchadmin;
            $branchadmin->user_id=$user->id;
            $branchadmin->branch_id=$user->branch_id;
            $branchadmin->save();
            return back()->with('success', 'Uğurlu! Istifadeci Əlavə Olundu.');


            }

            if ($request->type==3) {
            $reseption = new Reseption;
            $reseption->user_id=$user->id;
            $reseption->branch_id=$user->branch_id;
            $reseption->save();
            return back()->with('success', 'Uğurlu! Istifadeci Əlavə Olundu.');



            }

             if ($request->type==7) {
            $teacher = new Teacher;
            $teacher->user_id=$user->id;
            $teacher->group_id=$user->group_id;
            $teacher->branch_id=$user->branch_id;
            $teacher->save();
            return back()->with('success', 'Uğurlu! Istifadeci Əlavə Edildi.');


            }

            if ($request->type==1) {
            $Students = new Students;
            $Students->user_id=$user->id;
            $Students->branch_id=$user->branch_id;
            $Students->group_id=$user->group_id;
            $Students->kart_id=rand();
            $Students->save();
            return back()->with('success', 'Uğurlu! Istifadeci Əlavə Edildi.');



            }
            if ($request->type==2) {
            $Parents = new Parents;
            $Parents->user_id=$user->id;
            $Parents->branch_id=$user->branch_id;
            $Parents->group_id=$user->group_id;
            $Parents->save();
            return back()->with('success', 'Uğurlu! Istifadeci Əlavə Edildi.');



            }


            return back();

    }
      public function edit($id)
    {
            $user = User::find($id);
    $branch = Branch::all();
    $group = Group::all();

     if (Auth::user()->type==6) {
    $branch = Branch::all();

           $branch_id = Auth::user()->branch_id;
           $gro = Group::where('branch_id',$branch_id)->get();
    return view('users.create',compact('gro','branch'));



  }



    return view('users.edit',compact('user','branch','group'));

    }






    public function profile()
    {

        if ( Auth::user()->type==1) {
      $id = Auth::user()->id;


      $student = Students::where('user_id',$id)->first();

      $p = Invite::with('parents')->where('status','0')->where('student_id',$id)->first();
       return view('students.index',compact('parent','student','p'));
    }
        else{
        	return view('profile');
        }
}



public function profile_update(Request $request ){

            $user = Auth::user();
        $pass=$request->password;
        $password_repeat=$request->password_repeat;

         if ($pass==null) {

            $user->surname=$request->surname;
            $user->name=$request->name;
            $user->email=$request->email;
            $user->mobile=$request->mobile;
            $user->about=$request->about;
            $user->date=$request->date;


           if ($request->img!="") {
              $fileName           =$request->img->getClientOriginalName();
              $newName            =time().'_'.$fileName;
              $request->img->move('uploads/',$newName);


  }else{
              $newName            =$user->img;
          }

            $user->img=$newName;
            $user->save();

            return redirect('/profile');

        }



        else
        {
            $user->password=bcrypt($pass);
            $user->surname=$request->surname;
            $user->name=$request->name;
            $user->email=$request->email;
            $user->mobile=$request->mobile;
            $user->about=$request->about;
            $user->date=$request->date;


  if ($request->img!="") {
              $fileName           =$request->img->getClientOriginalName();
              $newName            =time().'_'.$fileName;
              $request->img->move('uploads/',$newName);


  }else{
              $newName            =$user->img;
          }

            $user->img=$newName;
            $user->save();


            $user->save();
            return redirect('/profile');
        }


 }

 public function update(Request $request,$id ){

      $user = User::find($id);
      $pass=$request->password;
      $password_repeat=$request->password_repeat;

      if ($pass==null) {

        $user->surname = $request->surname;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->mobile = $request->mobile;
        $user->about = $request->about;
        $user->date = $request->date;
        $user->group_id = $request->group_id;
        $user->branch_id = $request->branch_id;
        $user->type = $request->type;

      if ($request->img!="") {

        $fileName = $request->img->getClientOriginalName();
        $newName = time().'_'.$fileName;
        $request->img->move('uploads/',$newName);

      }else{
        $newName = $user->img;
      }
        $user->img=$newName;
        $user->save();
        return back()->with('success', 'Uğurlu! Məlumatlar Dəyişdirildi.');
  }



        else
        {
            $user->password=bcrypt($pass);
            $user->surname=$request->surname;
            $user->name=$request->name;
            $user->email=$request->email;
            $user->mobile=$request->mobile;
            $user->about=$request->about;
            $user->date=$request->date;
            $user->group_id=$request->group_id;
            $user->branch_id=$request->branch_id;



  if ($request->img!="") {
              $fileName           =$request->img->getClientOriginalName();
              $newName            =time().'_'.$fileName;
              $request->img->move('uploads/',$newName);


  }else{
              $newName            =$user->img;
          }

            $user->img=$newName;
            $user->save();



            return back()->with('success', 'Uğurlu! Məlumatlar Dəyişdirildi.');
        }


 }
 public function destroy($id)
    {
         $user = User::find($id);

        $user->delete();
        return back()->with('delete', 'Uğurlu! Istifadeci Silindi.');
        }

}

resources/views/users/edit.blade.php
@extends('layouts.app') @section('content')
<style type="text/css">
    label {
        right: 1vw;
    }
</style>

<div class="container">

    <div class="row">

        <div class="col-sm-12">
            <div class="white-box p-l-20 p-r-20">
              @if ($message = Session::get('success'))
              <div class="alert alert-success alert-block">
                  <button type="button" class="close" data-dismiss="alert">×</button>
                  <strong>{{ $message }}</strong>
              </div>
              @endif
                <div class="row">
                    <div class="col-md-12">
                        <form action="{{route('users.update', $user->id)}}" enctype="multipart/form-data" method="POST" class="form-horizontal">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <input type="hidden" name="_method" value="PATCH">
                            <div class="form-group">
                                <div class="col-md-6">
                                    <label class="col-md-12">Ad</label>

                                    <input placeholder="Ad" value="{{$user->name}}" name="name" type="text" class="form-control form-control-line"> </div>

                                <!-- user -->
                                <div class="col-md-6">
                                    <label class="col-md-12">Soyad</label>

                                    <input placeholder="Soyad" value="{{$user->surname}}" name="surname" type="text" class="form-control form-control-line"> </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6">
                                    <label class="col-md-12">Email</label>

                                    <input placeholder="e-mail" value="{{$user->email}}" type="email" id="example-email2" name="email" class="form-control form-control-line"> </div>

                                <!-- user -->
                                <div class="col-md-6">
                                    <label class="col-md-12">Şifrə </label>

                                    <input name="password" type="password" class="form-control form-control-line"> </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6">
                                    <label class="col-md-12">Mobil No</label>

                                    <input placeholder="Mobil No" value="{{$user->mobile}}" name="mobile" type="text" class="form-control form-control-line"> </div>
                                <div class="col-md-6">
                                    <label class="col-sm-6">Vəzifə</label>

                                    <select name="type" id="vezife" name="type" class="form-control form-control-line">
                                        <option disabled selected value="">-- Seçin --</option>
                                        @if(Auth::user()->type==6)
                                        <option {{$user->type == 3 ? 'selected' : ''}} value="3">Reseption</option>
                                        <option {{$user->type == 7 ? 'selected' : ''}} value="7">Müəllim</option>
                                        <option {{$user->type == 1 ? 'selected' : ''}} value="1">Tələbə</option>
                                        <option {{$user->type == 2 ? 'selected' : ''}} value="2">Valideyin</option>
                                        <option {{$user->type == 5 ? 'selected' : ''}} value="5">SMM</option>
                                        @endif @if(Auth::user()->type==0)
                                        <option {{$user->type == 6 ? 'selected' : ''}} value="6">Filial Rəhbəri</option>
                                        <option {{$user->type == 3 ? 'selected' : ''}} value="3">Reseption</option>
                                        <option {{$user->type == 7 ? 'selected' : ''}} value="7">Müəllim</option>
                                        <option {{$user->type == 1 ? 'selected' : ''}} value="1">Tələbə</option>
                                        <option {{$user->type == 2 ? 'selected' : ''}} value="2">Valideyin</option>
                                        <option {{$user->type == 5 ? 'selected' : ''}} value="5">SMM</option>
                                        @endif
                                    </select>
                                </div>
                            </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="col-sm-12">Filial</label>
                            <div style="padding-left: 0px;" class="col-md-12">
                                @if(Auth::user()->type==0)

                                <select id="filial" name="branch_id" class="form-control form-control-line">

                                    @foreach($branch as $branc)
                                    <option {{$user->branch_id == $branc->id ? 'selected' : ''}} value="{{$branc->id}}">{{$branc->name}}</option>
                                    @endforeach
                                </select>
                                @else
                                <select id="filial" name="branch_id" class="form-control form-control-line">

                                    <option  value="{{Auth::user()->branch_id}}">{{Auth::user()->branch->name}}</option>

                                </select>
                                @endif

                                <select id="qurup" style="display: none;" name="group_id" class="form-control form-control-line">
                                    @if(Auth::user()->type==0) @foreach($branch->all() as $branc)
                                    <optgroup label="{{$branc->name}}">
                                        @foreach($branc->group->all() as $grop)
                                        <option value="{{$grop->id}}">{{$grop->number}}</option>
                                        @endforeach
                                    </optgroup>
                                    @endforeach @else @foreach($gro as $grou)
                                    <option value="{{$grou->id}}">{{$grou->number}}</option>
                                    @endforeach @endif

                                </select>
                            </div>

                        </div>
                        <div class="col-md-6">
                            <label class="col-sm-12">Doğum Tarixi </label>
                            <div style="padding-left: 0px;" class="col-sm-12">
                                <input type="date" value="{{$user->date}}" name="date" class="form-control form-control-line" placeholder="Helping text">
                                <span class="help-block">
                                     <small>Məlumatları Yadda Saxlamaq Üçün Göndər  Düyməsini Sıx.</small></span> </div>
                        </div>
                    </div>
                    <div class="form-group">

                        <div class="col-sm-6">
                            <label>Şəkil Yüklə</label>

                            <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                <div class="form-control form-control-line" data-trigger="fileinput"> <i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span></div> <span class="input-group-addon btn btn-default btn-file"> <span class="fileinput-new"> Foto </span> <span class="fileinput-exists">Dəyiş</span>
                                <input type="file" name="img"> </span> <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">Sil</a> </div>
                        </div>

                        <div class="col-md-6">
                            <label>Haqqında</label>
                            <textarea style="height: 3.5vw;" name="about" class="form-control form-control-line">
                                {{$user->about}}
                            </textarea>
                            <br>
                        </div>
                    </div>
                    <div>
                        @if($user->img!=null)
                        <img src="/uploads/{{$user->img}}" width="180" class="img-responsive"> @else
                        <img src="/uploads/default.png" class="img-responsive" width="180"> @endif

                        <div class="form-group">

                            <div class="col-sm-4"></div>

                            <div class="col-sm-4">
                                <input type="submit" value="Göndər" class="btn btn-block btn-outline btn-info">
                            </div>
                        </div>

                    </div>

                    </form>

                    </form>

                </div>

            </div>

        </div>
    </div>
</div>

<script type="text/javascript">
    // $(document).ready(function(){
    $("#vezife").click(function() {
        $data = $("#vezife").val();
        // });

        if ($data == 7 || $data == 1 || $data == 2) {
            $("#filial").hide();

            $("#qurup").show();
            // alert($data);
        } else {
            $("#filial").show();

            $("#qurup").hide();

        }
    });
</script>
<!-- ent layout -->

@endsection

resources/views/users/index.blade.php
@extends('layouts.app') @section('content')
<div class="container">

    <div id="page-wrapper">
        <div class="container-fluid">

            <!-- /row -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="white-box">
                        <h3 class="box-title">Bütün İstifadəçilər</h3>

                        <div class="table-responsive">
                            <table class="table color-table primary-table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Ad</th>
                                        <th>Soyad</th>
                                        <th>E-Poçt</th>
                                        <th>Vəzifəsi</th>
                                        <th>Funksiya</th>
                                        <th></th>
                                        <th></th>
                                        <th></th>

                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach($users as $user)

                                    <tr>
                                        @if($user->type!=0)

                                        <td>{{$user->id}}</td>
                                        <td>{{$user->name}}</td>
                                        <td>{{$user->surname}}</td>

                                        <td>{{$user->email}}</td>

                                        <td>
                                            @if($user->type==5)
                                            <kbd>SMM</kbd> @endif

                                            @if($user->type==1)
                                            <kbd>Tələbə</kbd> @endif @if($user->type==2)
                                            <kbd>
                                            Valideyn
                                            </kbd> @endif @if($user->type==6) <kbd>Filial Rehberi</kbd> @endif @if($user->type==7)
                                            <kbd>Muellim</kbd> @endif @if($user->type==3)
                                            <kbd>Reseption</kbd> @endif
                                        </td>

                                        <td>
                                            <form action="/user/status/{{$user->id}}" method="POST">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}"> @if($user->status==0)
                                                <button value="1" name="status" type="submit" class="btn btn-success">Aktiv Et</button>
                                                @else
                                                <button value="0" name="status" type="submit" class="btn btn-danger">Deaktiv Et</button>
                                                @endif
                                            </form>
                                        </td>
                                        <td>
                                            <a href="/sertified/{{$user->id}}" class="btn btn-info">Sertifkatları</a>
                                        </td>



                                        <td>
                                            <a class="btn btn-success" href="/users/{{$user->id}}/edit/">
                                            Redakte Et
                                            </a>
                                        </td>
                                        <td>
                                            <form method="POST" action="{{route('users.destroy',$user->id)}}">
                                                {{csrf_field()}}
                                                <input type="hidden" name="_method" value="DELETE" />
                                                <button type="submit" class="btn btn-danger">Sil</button>

                                            </form>
                                        </td>
                                    </tr>
                                    @endif @endforeach

                                </tbody>
                            </table>
                            @if ($message = Session::get('success'))
                            <div class="alert alert-success alert-block">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                <strong>{{ $message }}</strong>
                            </div>
                            @endif
                        </div>
                    </div>
                </div>

            </div>

            @stop