routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::post('/new_register', 'UserController@new_register');

// Route::post('/registry', 'HomeController@register');

Auth::routes();
Route::group(['middleware' => ['auth']], function () {

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'HomeController@profile');

Route::get('teachers/{id}', 'HomeController@index_attendance');

Route::resource('branch', 'BranchController');
Route::resource('branchadmin', 'BranchadminController');
Route::resource('group', 'GroupController');
Route::resource('ruller', 'RullerController');
Route::get('ruller/view', 'RullerController@view');

Route::resource('parents', 'ParentsController');
Route::resource('students', 'StudentsController');

Route::resource('lesson', 'LessonController');


Route::get('profile', 'UserController@profile');
Route::post('profile/update', 'UserController@profile_update');
Route::get('sertified/{id}', 'SertifiedController@create');
Route::post('sertified/{id}', 'SertifiedController@store');
Route::get('sertified/delete/{id}', 'SertifiedController@destroy');

Route::get('/all_messages', 'ChatController@all_messages');




Route::get('/student/{id}', 'InviteController@check');

// Route::resource('reseption', 'ReseptionController');



Route::get('reseption/access', 'ReseptionController@access');
Route::post('reseption/{id}', 'ReseptionController@update');







// InviteController
Route::post('/invite/connect', 'InviteController@invite');

Route::resource('users', 'UserController');
Route::post('/user/status/{id}', 'HomeController@status');



Route::get('attendance/{id}', 'AttendanceController@index');
Route::post('/attendance/check', 'AttendanceController@check');


// ChatController

Route::get('/compose', 'ChatController@compose');
Route::get('/inbox', 'ChatController@inbox');
Route::get('/sent-mail', 'ChatController@sent_mail');

Route::get('/single-message/{id}', 'ChatController@messages_show');


Route::post('/compose/insert', 'ChatController@insert');


});

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
 protected $table="group";

 protected $fillable = [
        'number', 'branch_id',
    ];

  public function branch()
    {
        return $this->belongsTo('App\Branch');
    }



    }

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Group;
use App\Branch;


class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
   public function index()
    {
        $groups = Group::All();

        return view('group/index',compact('groups')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $branches = Branch::All();

        return view('group.create',compact('branches'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    
     if ($request->number=="") {

       return back()->with('unsuccess', 'Uğursuz! Qurup Nomresini Daxil Edin.');

        
     }else{
        $group = new Group;
        $group->number=$request->number;
        $group->branch_id=$request->branch_id;

        $group->save();

        return back()->with('success', 'Uğurlu! Qurup Əlavə Edildi.');
        
     }

 }
         
        
    

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $groups = Group::All();

        return view('group/index',compact('groups')); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $group = Group::find($id);
        $branches = Branch::All();

        return view('group/edit',compact('group','branches')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $groupes = Group::find($id);

        $groupes->number=$request->number;
        $groupes->branch_id=$request->branch_id;

        $groupes->save();

        return back()->with('success', 'Uğurlu! Qurup Redaktə Edildi.'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $group = Group::find($id);

        $group->delete();
        return back()->with('delete', 'Uğurlu! Qurup Silindi.'); 
    }
}

resources/views/group/create.blade.php
@extends('layouts.app')


@section('content')

<div class="container">

  <div class="row">
                    <div  style="text-align: center;" class="col-sm-12">
                        <div  class="white-box p-l-20 p-r-20">
                        <i  class="fa fa-users fa-5x"></i> 
                            <h3 class="box-title m-b-0">Qurup Əlavə Et</h3>
                          
                            <div class="row">
                                <div class="col-md-12">
                       <form action="{{url('/group')}}" enctype="multipart/form-data" method="POST" class="form-horizontal">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <div class="form-group">
                                             <div class="col-sm-4"></div>

                                            <div  class="col-md-4">
                                                <input placeholder="Qrup Nömrəsini Daxil Et" name="number" type="number" class="form-control form-control-line">
                                                 </div>
                                        </div> 
                                        @if(Auth::user()->type==0)
                                          <div class="form-group">
                                             <div class="col-sm-4"></div>
                                            <div class="col-sm-4">
                                        <select name="branch_id" class="form-group coursd" name="type">
            @foreach($branches as $branch)
              <option  value="{{$branch->id}}">{{$branch->name}}</option>
              @endforeach
            </select>
<br>

                            </div>
                                        </div>
                                        @else
                                        <input type="hidden" name="branch_id" value="{{Auth::user()->branch_id}}">

                                        @endif
                                        
                                        <div class="form-group">
                                             <div class="col-sm-4"></div>
                                            <div class="col-sm-4">
                                                <input type="submit" value="Göndər" class="btn btn-block btn-success" placeholder="Helping text"> 
                                                 </div>
                                        </div>

                                    </form>
                                       @if ($message = Session::get('success'))
                  <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button> 
                          <strong>{{ $message }}</strong>
                  </div>
                @endif
                @if ($message = Session::get('unsuccess'))
                  <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button> 
                          <strong>{{ $message }}</strong>
                  </div>
                @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

<!-- ent layout -->


@endsection

resources/views/group/edit.blade.php
@extends('layouts.app')


@section('content')

<div class="container">

  <div class="row">
                    <div  style="text-align: center;" class="col-sm-12">
                        <div  class="white-box p-l-20 p-r-20">
                        <i  class="fa fa-users fa-5x"></i> 
                            <h3 class="box-title m-b-0">Qurup Əlavə Et</h3>
                          
                            <div class="row">
                                <div class="col-md-12">
                       <form action="{{url('/group',['id'=>$group->id])}}" enctype="multipart/form-data" method="POST" class="form-horizontal">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    {{ method_field('PATCH') }}

                <div class="form-group">
                     <div class="col-sm-4"></div>

                    <div  class="col-md-4">
            <input placeholder="Qurup Nomresini Daxil Et" name="number" type="text" value="{{$group->number}}" class="form-control form-control-line">
             </div>
                </div> 
               

<div class="form-group">
                                             <div class="col-sm-4"></div>
                                            <div class="col-sm-4">
                                        <select name="branch_id" class="form-group coursd" name="type">
            @foreach($branches as $branch)
              <option  value="{{$branch->id}}">{{$branch->name}}</option>
              @endforeach
            </select>

                <div class="form-group">
                     <div class="col-sm-4"></div>
                    <div class="col-sm-4">
                        <input type="submit" value="Göndər" class="btn btn-block btn-success" placeholder="Helping text"> 
                         </div>
                </div>
                                    </form>
                                       @if ($message = Session::get('success'))
                  <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button> 
                          <strong>{{ $message }}</strong>
                  </div>
                @endif
               
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

<!-- ent layout -->


@endsection

resources/views/group/index.blade.php
@extends('layouts.app') @section('content')
<!-- start -->

<div class="container">

    <div id="page-wrapper">

        <div class="row">
            <div class="col-sm-12">
                <div class="white-box">
                    <h3 class="box-title">Sistemdə Olan Bütün Quruplar </h3>

                    <div class="table-responsive">
                        <table class="table color-table primary-table">
                            <thead>
                                <tr>

                                    <th>#</th>
                                    <th>Qurup Nömrəsi</th>
                                    <th>Qurupun Filialı</th>
                                    <th width="6%"><i class="fa fa-edit" aria-hidden="true"></i></th>
                                    <th width="6%"><i class="fa fa-trash-o" aria-hidden="true"></i></th>

                                </tr>
                            </thead>
                            <tbody>

                                @foreach ($groups as $group)
                                <tr>

                                    <td>1</td>
                                    <td>{{$group->number}}</td>
                                    <td>{{$group->branch->name}}</td>

                                    <td><a class="btn btn-warning" href="/group/{{$group->id}}/edit">Redaktə Et</a></td>
                                    <td>
                                        <form method="POST" action="{{ route('group.destroy', $group->id) }}">
                                            {{csrf_field()}}
                                            <input type="hidden" name="_method" value="DELETE" />
                                            <button type="submit" class="btn btn-danger">Sil</button>

                                        </form>
                                    </td>

                                </tr>
                                @endforeach

                            </tbody>

                        </table>
                        @if ($message = Session::get('delete'))
                        <div class="alert alert-success alert-block">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                        @endif
                    </div>
                </div>
            </div>

        </div>

        <!-- endlay out -->
        @stop

resources/views/group/show.blade.php
show.blade.php