routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::post('/new_register', 'UserController@new_register');

// Route::post('/registry', 'HomeController@register');

Auth::routes();
Route::group(['middleware' => ['auth']], function () {

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'HomeController@profile');

Route::get('teachers/{id}', 'HomeController@index_attendance');

Route::resource('branch', 'BranchController');
Route::resource('branchadmin', 'BranchadminController');
Route::resource('group', 'GroupController');
Route::resource('ruller', 'RullerController');
Route::get('ruller/view', 'RullerController@view');

Route::resource('parents', 'ParentsController');
Route::resource('students', 'StudentsController');

Route::resource('lesson', 'LessonController');


Route::get('profile', 'UserController@profile');
Route::post('profile/update', 'UserController@profile_update');
Route::get('sertified/{id}', 'SertifiedController@create');
Route::post('sertified/{id}', 'SertifiedController@store');
Route::get('sertified/delete/{id}', 'SertifiedController@destroy');

Route::get('/all_messages', 'ChatController@all_messages');




Route::get('/student/{id}', 'InviteController@check');

// Route::resource('reseption', 'ReseptionController');



Route::get('reseption/access', 'ReseptionController@access');
Route::post('reseption/{id}', 'ReseptionController@update');







// InviteController
Route::post('/invite/connect', 'InviteController@invite');

Route::resource('users', 'UserController');
Route::post('/user/status/{id}', 'HomeController@status');



Route::get('attendance/{id}', 'AttendanceController@index');
Route::post('/attendance/check', 'AttendanceController@check');


// ChatController

Route::get('/compose', 'ChatController@compose');
Route::get('/inbox', 'ChatController@inbox');
Route::get('/sent-mail', 'ChatController@sent_mail');

Route::get('/single-message/{id}', 'ChatController@messages_show');


Route::post('/compose/insert', 'ChatController@insert');


});

app/Branch.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Branch extends Model
{
 	protected $table="branch";


 	 public function group()
    {
        return $this->hasMany('App\Group');
    }
}

app/Http/Controllers/BranchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Branch;

class BranchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $branches = Branch::All();

        return view('branch/index',compact('branches')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('branch.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    
     if ($request->name=="") {

       return back()->with('unsuccess', 'Uğursuz! Filial Adını Daxil Edin.');

        
     }else{
        $branch = new Branch;
        $branch->name=$request->name;
        $branch->save();

        return back()->with('success', 'Uğurlu! Filial Əlavə Edildi.');
        
     }

 }
         
        
    

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $branches = Branch::All();

        return view('branch/index',compact('branches')); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $branch = Branch::find($id);

        return view('branch/edit',compact('branch')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $branches = Branch::find($id);

        $branches->name=$request->name;

        $branches->save();

        return back()->with('success', 'Uğurlu! Filial Redaktə Edildi.'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    $branch = Branch::find($id);

        $branch->delete();
        return back()->with('delete', 'Uğurlu! Filial Silindi.'); 
    }
}

resources/views/branch/create.blade.php
@extends('layouts.app')


@section('content')

<div class="container">

  <div class="row">
                    <div  style="text-align: center;" class="col-sm-12">
                        <div  class="white-box p-l-20 p-r-20">
                        <i  class="fa fa-users fa-5x"></i> 
                            <h3 class="box-title m-b-0">Filial Əlavə Et</h3>
                          
                            <div class="row">
                                <div class="col-md-12">
                       <form action="{{url('/branch')}}" enctype="multipart/form-data" method="POST" class="form-horizontal">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <div class="form-group">
                                             <div class="col-sm-4"></div>

                                            <div  class="col-md-4">
                                                <input placeholder="Filial Adını Daxil Et" name="name" type="text" class="form-control form-control-line">
                                                 </div>
                                        </div> 
                                        
                                        <div class="form-group">
                                             <div class="col-sm-4"></div>
                                            <div class="col-sm-4">
                                                <input type="submit" value="Göndər" class="btn btn-block btn-success" placeholder="Helping text"> 
                                                 </div>
                                        </div>

                                    </form>
                                       @if ($message = Session::get('success'))
                  <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button> 
                          <strong>{{ $message }}</strong>
                  </div>
                @endif
                @if ($message = Session::get('unsuccess'))
                  <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button> 
                          <strong>{{ $message }}</strong>
                  </div>
                @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

<!-- ent layout -->


@endsection

resources/views/branch/edit.blade.php
@extends('layouts.app')


@section('content')

<div class="container">

  <div class="row">
                    <div  style="text-align: center;" class="col-sm-12">
                        <div  class="white-box p-l-20 p-r-20">
                        <i  class="fa fa-users fa-5x"></i> 
                            <h3 class="box-title m-b-0">Filial Əlavə Et</h3>
                          
                            <div class="row">
                                <div class="col-md-12">
                       <form action="{{url('/branch',['id'=>$branch->id])}}" enctype="multipart/form-data" method="POST" class="form-horizontal">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    {{ method_field('PATCH') }}

                <div class="form-group">
                     <div class="col-sm-4"></div>

                    <div  class="col-md-4">
            <input placeholder="Filial Adını Daxil Et" name="name" type="text" value="{{$branch->name}}" class="form-control form-control-line">
             </div>
                </div> 
                
                <div class="form-group">
                     <div class="col-sm-4"></div>
                    <div class="col-sm-4">
                        <input type="submit" value="Göndər" class="btn btn-block btn-success" placeholder="Helping text"> 
                         </div>
                </div>

                                    </form>
                                       @if ($message = Session::get('success'))
                  <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button> 
                          <strong>{{ $message }}</strong>
                  </div>
                @endif
               
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

<!-- ent layout -->


@endsection

resources/views/branch/index.blade.php
@extends('layouts.app')


@section('content')
<!-- start -->

<div class="container">

    <div id="page-wrapper">
            
    <div class="row">
        <div class="col-sm-12">
            <div class="white-box">
                <h3 class="box-title">Sistemdə Olan Bütün Filiallar </h3>
               
                <div class="table-responsive">
                    <table class="table color-table primary-table">
                        <thead>
                            <tr>
                                
                                <th>#</th>
                                <th>Filial Adı</th>
                               <th><i class="fa fa-edit" aria-hidden="true"></i></th>
                                
                               <th><i class="fa fa-trash-o" aria-hidden="true"></i></th>

                      

                            </tr>
                        </thead>
                        <tbody>

                        
                        @foreach ($branches as $branc)
                            <tr>
                         
                                <td>1</td>
                                <td>{{$branc->name}}</td>
                           
                                <td><a class="btn btn-warning" href="/branch/{{$branc->id}}/edit">Redaktə Et</a></td>
                             
<td>
                                   <form method="POST" action="{{ route('branch.destroy', $branc->id) }}">
                                   {{csrf_field()}}
    <input type="hidden" name="_method" value="DELETE" />
    <button type="submit" class="btn btn-danger">Sil</button>

</form>
</td>   


                               

                                
                             
                            
                            </tr>
                            @endforeach


                          
                     	
                        </tbody>
                    </table>
                    @if ($message = Session::get('delete'))
                  <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button> 
                          <strong>{{ $message }}</strong>
                  </div>
                @endif
                </div>
            </div>
        </div>
        
       
    </div>




<!-- endlay out -->
@stop

resources/views/branch/show.blade.php
show.blade.php